"""auto

Revision ID: 67fa3417bd7c
Revises: b7e2a1d0c9f8
Create Date: 2026-05-08 04:27:10.124277

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "67fa3417bd7c"
down_revision: str | Sequence[str] | None = "b7e2a1d0c9f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
